package com.monteweb.auth.internal.controller;

import com.monteweb.auth.internal.service.JwtService;
import com.monteweb.auth.internal.service.OidcAuthCodeStore;
import com.monteweb.auth.internal.service.OidcUserService;
import com.monteweb.auth.internal.service.RefreshTokenService;
import com.monteweb.shared.dto.ApiResponse;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.http.ResponseEntity;
import org.springframework.security.oauth2.client.registration.ClientRegistrationRepository;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

/**
 * Handles OIDC/SSO authentication flow.
 *
 * Secure flow:
 * 1. Frontend calls GET /api/v1/auth/oidc/config to get available providers
 * 2. Frontend redirects to /oauth2/authorization/{provider}
 * 3. Spring Security handles the OAuth2 flow and callback
 * 4. OidcAuthenticationSuccessHandler stores verified claims in Redis with a one-time code
 * 5. Handler redirects to frontend with the code
 * 6. Frontend exchanges the code via POST /api/v1/auth/oidc/token
 */
@RestController
@RequestMapping("/api/v1/auth/oidc")
@ConditionalOnProperty(prefix = "monteweb.oidc", name = "enabled", havingValue = "true")
public class OidcAuthController {

    private final OidcUserService oidcUserService;
    private final JwtService jwtService;
    private final RefreshTokenService refreshTokenService;
    private final ClientRegistrationRepository clientRegistrationRepository;
    private final OidcAuthCodeStore oidcAuthCodeStore;

    @Value("${monteweb.oidc.provider-name:oidc}")
    private String providerName;

    public OidcAuthController(OidcUserService oidcUserService,
                               JwtService jwtService,
                               RefreshTokenService refreshTokenService,
                               ClientRegistrationRepository clientRegistrationRepository,
                               OidcAuthCodeStore oidcAuthCodeStore) {
        this.oidcUserService = oidcUserService;
        this.jwtService = jwtService;
        this.refreshTokenService = refreshTokenService;
        this.clientRegistrationRepository = clientRegistrationRepository;
        this.oidcAuthCodeStore = oidcAuthCodeStore;
    }

    /**
     * Returns OIDC configuration for the frontend.
     */
    @GetMapping("/config")
    public ResponseEntity<ApiResponse<Map<String, Object>>> getConfig() {
        var registration = clientRegistrationRepository.findByRegistrationId(providerName);
        if (registration == null) {
            return ResponseEntity.ok(ApiResponse.ok(Map.of("enabled", false)));
        }

        return ResponseEntity.ok(ApiResponse.ok(Map.of(
                "enabled", true,
                "provider", providerName,
                "authorizationUri", "/oauth2/authorization/" + providerName
        )));
    }

    /**
     * Exchanges a server-verified one-time OIDC code for application JWT tokens.
     * The code is generated by OidcAuthenticationSuccessHandler after a verified OAuth2 flow.
     */
    @PostMapping("/token")
    public ResponseEntity<ApiResponse<Map<String, Object>>> exchangeToken(
            @RequestBody OidcTokenRequest request) {
        if (request.code() == null || request.code().isBlank()) {
            throw new com.monteweb.shared.exception.BusinessException("Missing OIDC auth code");
        }

        var claims = oidcAuthCodeStore.consumeCode(request.code());
        if (claims == null) {
            throw new com.monteweb.shared.exception.BusinessException("Invalid or expired OIDC auth code");
        }

        var user = oidcUserService.resolveUser(
                claims.provider(),
                claims.subject(),
                claims.email(),
                claims.firstName(),
                claims.lastName()
        );

        String accessToken = jwtService.generateAccessToken(
                user.id(), user.email(), user.role().name());
        String refreshToken = refreshTokenService.createRefreshToken(user.id());

        return ResponseEntity.ok(ApiResponse.ok(Map.of(
                "accessToken", accessToken,
                "refreshToken", refreshToken,
                "userId", user.id(),
                "email", user.email(),
                "role", user.role().name()
        )));
    }

    /**
     * Request body for OIDC token exchange.
     * Only accepts a server-generated one-time code (not raw user claims).
     */
    public record OidcTokenRequest(
            String code
    ) {}
}
